import React, { useRef } from 'react';
import { DashboardData, UserSession } from '../types';
import { FileText, Printer, Download, X, Shield, CheckCircle, AlertTriangle } from 'lucide-react';

interface IAPReportModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: DashboardData;
  session?: UserSession | null;
}

export const IAPReportModal: React.FC<IAPReportModalProps> = ({
  isOpen,
  onClose,
  data,
  session,
}) => {
  const printAreaRef = useRef<HTMLDivElement>(null);

  if (!isOpen) return null;

  const { metrics, incidents, resources, last_replan_event, timeline } = data;
  const activeIncidents = incidents.filter((i) => i.status !== 'resolved');
  const nowStr = new Date().toLocaleString();

  const handlePrint = () => {
    window.print();
  };

  const handleDownloadMarkdown = () => {
    const md = `# FEMA FORM ICS-201: INCIDENT BRIEFING & ACTION PLAN
**Operational Period:** ${nowStr}
**Incident Commander:** ${session?.displayName || 'Incident Commander Marcus Vance'}
**Badge / Station:** ${session?.badgeNumber || 'HQ-001'} | Central Tactical Command
**Approval Status:** ${metrics.approval_status.toUpperCase()}

---

## 1. SITUATION SUMMARY
- **Total Active Emergencies:** ${metrics.active_incidents_count}
- **Critical Incidents (Priority > 85.0):** ${metrics.critical_incidents_count}
- **Total Available Reserves:** ${metrics.available_ambulances} Ambulances | ${metrics.available_rescue_teams} Rescue Teams | ${metrics.available_medical_units} Trauma Units
- **Deployed Fleet Units:** ${metrics.resources_currently_assigned} of ${metrics.total_resources} Total Assets

---

## 2. ACTIVE INCIDENT TRIAGE ROSTER
| Incident ID | Emergency Scene | Severity | Urgency | Casualties | Priority Score | Allocated Apparatus |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
${activeIncidents
  .map(
    (inc) =>
      `| **${inc.incident_id}** | ${inc.title} (${inc.location}) | ${inc.severity}/10 | ${inc.urgency}/10 | ${inc.estimated_casualties} | ${inc.priority_score.toFixed(1)} | ${inc.allocated_resources.join(', ') || 'Pending'} |`
  )
  .join('\n')}

---

## 3. RESOURCE FLEET STATUS & FIELD ASSIGNMENTS
| Resource ID | Unit Name | Type | Home Base | Status | Current Assignment |
| :--- | :--- | :--- | :--- | :--- | :--- |
${resources
  .map(
    (res) =>
      `| **${res.resource_id}** | ${res.name} | ${res.resource_type.toUpperCase()} | ${res.location} | ${res.status.toUpperCase()} | ${res.assigned_incident_id || 'Standby Reserve'} |`
  )
  .join('\n')}

---

## 4. DYNAMIC MULTI-AGENT REALLOCATION AUDIT
${
  last_replan_event && last_replan_event.changes && last_replan_event.changes.length > 0
    ? last_replan_event.changes
        .map(
          (c, idx) =>
            `${idx + 1}. **${c.resource_name} (${c.resource_id})**: Reallocated from *${c.previous_incident_title}* ➔ *${c.new_incident_title}* [Reason: ${c.reason}]`
        )
        .join('\n')
    : 'No active dynamic preemption shifts detected in current operational period.'
}

---

## 5. COMMANDER SAFETY & HUMAN-IN-THE-LOOP APPROVAL
- **Human Approval Flagged:** ${metrics.human_approval_required ? 'YES (Critical Life-Safety Shifts Detected)' : 'NO (Fully Autonomous Reallocation)'}
- **Approval Decision:** ${metrics.approval_status.toUpperCase()}
- **Sign-Off Authority:** ${session?.displayName || 'Crisis Commander Marcus Vance'}
- **Generated by:** Crisis Command Multi-Agent StateGraph Platform
`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `FEMA-ICS-201-Incident-Action-Plan-${new Date().toISOString().slice(0, 10)}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-3 sm:p-6 overflow-y-auto">
      <div className="relative hud-panel rounded-2xl max-w-4xl w-full p-6 sm:p-8 border border-sky-500/40 shadow-2xl my-auto max-h-[90vh] flex flex-col">
        {/* Corner Brackets */}
        <div className="corner-bracket-tl" />
        <div className="corner-bracket-tr" />
        <div className="corner-bracket-bl" />
        <div className="corner-bracket-br" />

        {/* Modal Header */}
        <div className="flex items-center justify-between pb-4 mb-4 border-b border-slate-800 shrink-0">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 rounded-xl bg-sky-500/10 border border-sky-500/30 text-sky-400">
              <FileText className="w-5 h-5 text-sky-400" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-black text-white uppercase tracking-wider flex items-center gap-2">
                <span>FEMA FORM ICS-201 // INCIDENT ACTION PLAN</span>
                <span className="text-[10px] px-2 py-0.5 rounded bg-emerald-950/80 border border-emerald-500/40 text-emerald-400 font-mono font-bold">
                  OFFICIAL BRIEF
                </span>
              </h2>
              <p className="text-xs text-slate-400 font-mono">
                Standard Incident Command System (ICS) Operational Summary & Resource Matrix
              </p>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <button
              onClick={handlePrint}
              className="p-2 rounded-lg bg-slate-900 hover:bg-slate-800 text-slate-300 hover:text-white border border-slate-700 text-xs font-semibold flex items-center gap-1.5 transition active:scale-95"
              title="Print or Save as PDF"
            >
              <Printer className="w-4 h-4 text-sky-400" />
              <span className="hidden sm:inline">Print / PDF</span>
            </button>
            <button
              onClick={handleDownloadMarkdown}
              className="p-2 rounded-lg bg-sky-600 hover:bg-sky-500 text-white text-xs font-semibold flex items-center gap-1.5 transition active:scale-95 shadow-md"
              title="Download Markdown Report"
            >
              <Download className="w-4 h-4" />
              <span className="hidden sm:inline">Download MD</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg hover:bg-slate-800 text-slate-400 hover:text-white transition"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable IAP Document Body */}
        <div ref={printAreaRef} className="flex-1 overflow-y-auto pr-1 space-y-6 text-slate-200 text-xs font-sans">
          {/* IAP Top Metadata Bar */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 p-3.5 bg-slate-950/70 border border-slate-800 rounded-xl font-mono text-[11px]">
            <div>
              <span className="text-slate-500 uppercase block text-[9px]">Operational Period:</span>
              <strong className="text-white">{nowStr}</strong>
            </div>
            <div>
              <span className="text-slate-500 uppercase block text-[9px]">Incident Commander:</span>
              <strong className="text-sky-300">{session?.displayName || 'Commander Marcus Vance'}</strong>
            </div>
            <div>
              <span className="text-slate-500 uppercase block text-[9px]">Station Badge:</span>
              <strong className="text-emerald-400">{session?.badgeNumber || 'HQ-001'}</strong>
            </div>
            <div>
              <span className="text-slate-500 uppercase block text-[9px]">Approval Status:</span>
              <span className={`inline-block px-2 py-0.5 rounded font-bold uppercase text-[10px] ${
                metrics.approval_status === 'approved' 
                  ? 'bg-emerald-950 text-emerald-300 border border-emerald-500/40' 
                  : 'bg-amber-950 text-amber-300 border border-amber-500/40'
              }`}>
                {metrics.approval_status}
              </span>
            </div>
          </div>

          {/* Section 1: Executive Situation Metrics */}
          <div>
            <h3 className="text-xs font-black uppercase text-sky-400 tracking-wider mb-2 font-mono flex items-center gap-1.5">
              <span>1. Situation Assessment & Fleet Status</span>
            </h3>
            <div className="grid grid-cols-3 sm:grid-cols-6 gap-2 font-mono">
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-center">
                <div className="text-lg font-black text-white">{metrics.active_incidents_count}</div>
                <div className="text-[9px] text-slate-400 uppercase">Active Crises</div>
              </div>
              <div className="p-2.5 rounded-lg bg-red-950/40 border border-red-500/30 text-center">
                <div className="text-lg font-black text-red-400">{metrics.critical_incidents_count}</div>
                <div className="text-[9px] text-red-300 uppercase">Critical &gt;85</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-center">
                <div className="text-lg font-black text-emerald-400">{metrics.available_ambulances}</div>
                <div className="text-[9px] text-slate-400 uppercase">Res. Ambulances</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-center">
                <div className="text-lg font-black text-sky-400">{metrics.available_rescue_teams}</div>
                <div className="text-[9px] text-slate-400 uppercase">Res. SAR Teams</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-center">
                <div className="text-lg font-black text-purple-400">{metrics.available_medical_units}</div>
                <div className="text-[9px] text-slate-400 uppercase">Res. Trauma</div>
              </div>
              <div className="p-2.5 rounded-lg bg-slate-900/60 border border-slate-800 text-center">
                <div className="text-lg font-black text-cyan-400">{metrics.resources_currently_assigned}</div>
                <div className="text-[9px] text-slate-400 uppercase">Deployed Units</div>
              </div>
            </div>
          </div>

          {/* Section 2: Active Incident Triage Matrix */}
          <div>
            <h3 className="text-xs font-black uppercase text-sky-400 tracking-wider mb-2 font-mono flex items-center gap-1.5">
              <span>2. Active Incidents & Priority Triage Roster</span>
            </h3>
            <div className="overflow-x-auto rounded-xl border border-slate-800">
              <table className="w-full text-left font-mono text-[11px]">
                <thead className="bg-slate-900/80 text-slate-400 uppercase text-[9px] border-b border-slate-800">
                  <tr>
                    <th className="p-2.5">ID</th>
                    <th className="p-2.5">Incident Title</th>
                    <th className="p-2.5">Location</th>
                    <th className="p-2.5">Priority</th>
                    <th className="p-2.5">Casualties</th>
                    <th className="p-2.5">Allocated Units</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800/60 bg-slate-950/40">
                  {activeIncidents.map((inc) => (
                    <tr key={inc.incident_id} className="hover:bg-slate-900/50">
                      <td className="p-2.5 font-bold text-white">{inc.incident_id}</td>
                      <td className="p-2.5 font-sans font-bold text-slate-200">{inc.title}</td>
                      <td className="p-2.5 text-slate-400">📍 {inc.location}</td>
                      <td className="p-2.5">
                        <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold ${
                          inc.priority_level === 'CRITICAL' ? 'bg-red-950 text-red-400 border border-red-500/30' : 'bg-amber-950 text-amber-400'
                        }`}>
                          {inc.priority_level} ({inc.priority_score.toFixed(1)})
                        </span>
                      </td>
                      <td className="p-2.5 font-bold text-red-400">{inc.estimated_casualties}</td>
                      <td className="p-2.5">
                        <div className="flex flex-wrap gap-1">
                          {inc.allocated_resources.map((r) => (
                            <span key={r} className="px-1.5 py-0.5 rounded bg-sky-950 text-sky-300 border border-sky-500/30 text-[9px]">
                              {r}
                            </span>
                          ))}
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Section 3: Reallocation & Preemption Log */}
          <div>
            <h3 className="text-xs font-black uppercase text-sky-400 tracking-wider mb-2 font-mono flex items-center gap-1.5">
              <span>3. Multi-Agent Reallocation Audit Trail</span>
            </h3>
            <div className="space-y-1.5 p-3 rounded-xl bg-slate-950/60 border border-slate-800 font-mono text-[10px]">
              {last_replan_event && last_replan_event.changes && last_replan_event.changes.length > 0 ? (
                last_replan_event.changes.map((c, idx) => (
                  <div key={idx} className="flex items-start space-x-2 text-slate-300 py-1 border-b border-slate-900 last:border-0">
                    <span className="text-amber-400 font-bold shrink-0">#{idx + 1}</span>
                    <div>
                      <strong>{c.resource_name} ({c.resource_id})</strong>: Shifted from <span className="text-slate-400">{c.previous_incident_title}</span> ➔ <span className="text-sky-300 font-bold">{c.new_incident_title}</span>
                      <div className="text-[9px] text-slate-500 mt-0.5 italic">Rationale: {c.reason}</div>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-slate-500 py-2 text-center">
                  All active units verified. Zero preemption conflicts in current snapshot.
                </div>
              )}
            </div>
          </div>

          {/* Section 4: Human-in-the-Loop Sign-off Block */}
          <div className="p-4 rounded-xl bg-gradient-to-r from-sky-950/40 via-slate-900/60 to-slate-950/40 border border-sky-500/30 flex flex-col sm:flex-row items-center justify-between gap-4 font-mono">
            <div>
              <div className="text-xs font-bold text-white flex items-center gap-2">
                <Shield className="w-4 h-4 text-sky-400" />
                <span>COMMANDER SIGN-OFF & OPERATIONAL AUTHORIZATION</span>
              </div>
              <div className="text-[10px] text-slate-400 mt-1">
                Authorized By: <strong>{session?.displayName || 'Commander Marcus Vance'}</strong> &bull; {nowStr}
              </div>
            </div>

            <div className="flex items-center space-x-2">
              <span className="w-2.5 h-2.5 rounded-full bg-emerald-400 animate-pulse" />
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-wide">
                OPERATIONAL POSTURE CONFIRMED
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
